name: Build and Deploy Github Page
on:
  repository_dispatch:
    types: [update_config]
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        deploy_branch: gh-pages # The branch the action should deploy to.
        angular_dist_build_folder: dist/sound-buttons # The folder where your project is supposed to be after running ng build by the action.
