# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
# Workaround: https://github.com/redhat-developer/vscode-yaml/issues/397

name: Build and Deploy to Github Page
on:
  repository_dispatch:
    types: [update_config]
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo on master
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Checkout submodules to latest
      run: git submodule update --init --recursive && git submodule update --recursive --remote

    # This is specifically for Scully
    - name: Build angular project and publish to github page (Scully)
      uses: cmgriffing/scully-gh-pages-action@v9
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        deploy-branch: gh-pages # The branch the action should deploy to.

    # # This is for normal Angular project
    # - name: Build angular project and publish to github page
    #   uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
    #   with:
    #     github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
    #     build_configuration: production # The build environment for the app. please look configurations in your angular.json
    #     deploy_branch: gh-pages # The branch the action should deploy to.
    #     angular_dist_build_folder: dist/sound-buttons # The folder where your project is supposed to be after running ng build by the action.

    - name: Publish to IPFS
      uses: sha224/ipfs-publisher@v1
      env:
        DEFAULT_BRANCH: gh-pages
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        DOMAIN: ipfs.sound-buttons
        PINATA_TOKEN: ${{ secrets.PINATA_TOKEN }}
        CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
        CLOUDFLARE_ZONEID: ${{ secrets.CLOUDFLARE_ZONEID }}
