name: Build and Deploy to Github Page
on:
  repository_dispatch:
    types: [update_config]
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo on master
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Check out submodules on master
      uses: actions/checkout@v2
      with:
        repository: jim60105/sound-buttons_configs
        path: src/assets/configs
        ref: master

    - name: Build angular project and publish to github page
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        deploy_branch: gh-pages # The branch the action should deploy to.
        angular_dist_build_folder: dist/sound-buttons # The folder where your project is supposed to be after running ng build by the action.
